import { ALLOWED_IMAGE_TYPES, MAX_IMAGE_BYTES } from "@/lib/products/image-constants";
import { validateAffiliateUrl, validateProductName } from "@/lib/products/validation";
import { CSV_MAX_ROWS, parseCsv } from "./csv";
import { MAX_CATEGORIES_PER_ROW, resolveCategories, splitCategoryCell, type CategoryRef } from "./categories";
import { checkCsvImageFilename, claimedTypeFromName, type SniffedType } from "./images";

// Everything the Owner bulk import needs to decide "is this batch importable?".
// Used twice with identical results: once for the whole-batch preview, and
// again per row inside the import action (the server never trusts that the
// preview was honest, since the import request is client-initiated).
//
// Duplicate rule — deliberately NOT a new business rule. The database already
// defines product identity as the slug (`products.slug` UNIQUE, generated from
// the name by slugify() and made collision-safe by next_unique_slug(), which
// silently appends -2, -3…). That silent suffixing is exactly how an
// accidental re-import would create "Prodentim-2". So a "duplicate" here means
// "importing this would collide on the slug the DB would have generated":
//   • another row in the same CSV with the same slug base / name, or
//   • an existing, non-deleted product whose slug equals that base.
// slugBase() mirrors public.slugify() and is used ONLY to detect the collision;
// the real slug is still generated by the database.

export const REQUIRED_COLUMNS = ["product_name", "affiliate_url", "image_filename"] as const;
/**
 * Optional category column. "category" (one) and "categories" (one or more,
 * separated by ";") are the same feature under two names - the plain
 * 3-column CSV keeps working unchanged. A blank cell means "no category".
 */
export const CATEGORY_COLUMNS = ["category", "categories"] as const;

/** Mirrors public.slugify(): lowercase, non-alphanumerics to '-', collapse, trim. Empty means "can't compare". */
export function slugBase(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/-{2,}/g, "-").replace(/^-+|-+$/g, "");
}

export type ManifestImage = {
  /** Basename as supplied (from a ZIP entry or a picked file). */
  name: string;
  /** Real byte length measured in the browser (not a header claim). */
  size: number;
  /** Type sniffed from the file's leading bytes; null = not a supported image. */
  sniffed: SniffedType | null;
  /** Set when the browser could not read the file safely. */
  problem?: "too-large" | "unreadable";
};

export type ParsedRow = {
  line: number;
  name: string;
  affiliateUrl: string;
  imageFilename: string;
  /** Category names as written in the CSV (split on ";"), before database matching. */
  categoryNames: string[];
  /** Field-level problems found without looking at images or the database. */
  errors: string[];
  urlStatus: "valid" | "invalid" | "missing";
  urlHost: string | null;
  urlInsecure: boolean;
  duplicateOfLine: number | null;
  base: string;
};

export type ParsedBatch = {
  fatal: string | null;
  rows: ParsedRow[];
  /** True when the CSV has a category/categories column (so the DB catalogue is needed). */
  hasCategoryColumn: boolean;
};

export function parseBulkRows(csvText: string): ParsedBatch {
  const parsed = parseCsv(csvText);
  if (parsed.error) return { fatal: parsed.error, rows: [], hasCategoryColumn: false };

  const header = parsed.header;
  const fail = (fatal: string): ParsedBatch => ({ fatal, rows: [], hasCategoryColumn: false });
  const allowed: readonly string[] = [...REQUIRED_COLUMNS, ...CATEGORY_COLUMNS];
  const missing = REQUIRED_COLUMNS.filter((c) => !header.includes(c));
  const unexpected = header.filter((c) => !allowed.includes(c));
  const expected = `${REQUIRED_COLUMNS.join(",")}[,category]`;
  if (missing.length > 0) return fail(`The header row is missing: ${missing.join(", ")}. Expected: ${expected}.`);
  if (unexpected.length > 0) return fail(`Unexpected column(s): ${unexpected.join(", ")}. Expected: ${expected}.`);
  if (new Set(header).size !== header.length) return fail("The header row repeats a column name.");
  if (CATEGORY_COLUMNS.every((c) => header.includes(c))) return fail("Use either a category column or a categories column, not both.");
  if (parsed.rows.length === 0) return fail("The CSV has a header but no products.");
  if (parsed.rows.length > CSV_MAX_ROWS) return fail(`Too many rows: ${parsed.rows.length}. Import at most ${CSV_MAX_ROWS} products at a time.`);
  const categoryColumn = CATEGORY_COLUMNS.find((c) => header.includes(c));

  const col = (cells: string[], name: string) => cells[header.indexOf(name)] ?? "";
  const seenBases = new Map<string, number>();
  const seenNames = new Map<string, number>();
  const rows: ParsedRow[] = parsed.rows.map(({ line, cells }) => {
    const errors: string[] = [];
    if (cells.length > header.length) {
      errors.push("Too many columns — a product name containing a comma must be wrapped in double quotes.");
    }

    const nameCheck = validateProductName(col(cells, "product_name"));
    if (!nameCheck.ok) errors.push(`Product name: ${nameCheck.error}`);
    const name = nameCheck.ok ? nameCheck.value : col(cells, "product_name");

    const rawUrl = col(cells, "affiliate_url");
    const urlCheck = validateAffiliateUrl(rawUrl);
    let urlStatus: ParsedRow["urlStatus"] = "valid";
    let urlHost: string | null = null;
    let urlInsecure = false;
    if (!urlCheck.ok) {
      urlStatus = rawUrl.trim() === "" ? "missing" : "invalid";
      errors.push(`Affiliate URL: ${urlCheck.error}`);
    } else {
      const u = new URL(urlCheck.value);
      urlHost = u.hostname;
      urlInsecure = u.protocol === "http:";
      if (u.username || u.password) {
        urlStatus = "invalid";
        errors.push("Affiliate URL: remove the username/password from the URL.");
      }
    }

    const categoryNames = categoryColumn ? splitCategoryCell(col(cells, categoryColumn)) : [];
    if (categoryNames.length > MAX_CATEGORIES_PER_ROW) {
      errors.push(`Category: at most ${MAX_CATEGORIES_PER_ROW} categories per product.`);
    }

    const fnCheck = checkCsvImageFilename(col(cells, "image_filename"));
    if (!fnCheck.ok) errors.push(`Image: ${fnCheck.error}`);
    const imageFilename = fnCheck.ok ? fnCheck.name : col(cells, "image_filename");

    let duplicateOfLine: number | null = null;
    const base = nameCheck.ok ? slugBase(nameCheck.value) : "";
    if (nameCheck.ok) {
      const nameKey = nameCheck.value.toLowerCase();
      const prior = seenNames.get(nameKey) ?? (base ? seenBases.get(base) : undefined);
      if (prior !== undefined) {
        duplicateOfLine = prior;
        errors.push(`Duplicate product: same name as line ${prior} in this CSV.`);
      } else {
        seenNames.set(nameKey, line);
        if (base) seenBases.set(base, line);
      }
    }

    return {
      line,
      name,
      affiliateUrl: urlCheck.ok ? urlCheck.value : rawUrl,
      imageFilename,
      categoryNames,
      errors,
      urlStatus,
      urlHost,
      urlInsecure,
      duplicateOfLine,
      base,
    };
  });
  return { fatal: null, rows, hasCategoryColumn: Boolean(categoryColumn) };
}

/** Category validation against the database catalogue. Returns problems only; matching ids come from resolveCategories(). */
export function categoryErrors(row: Pick<ParsedRow, "categoryNames">, catalog: CategoryRef[]): string[] {
  return resolveCategories(row.categoryNames, catalog).notFound.map((name) => `Category not found: ${name}`);
}

export type ImageMatch =
  | { status: "matched"; image: ManifestImage }
  | { status: "missing" | "ambiguous" | "unsupported" | "too-large" | "mismatch" | "unreadable"; message: string };

/**
 * Finds the uploaded file for a CSV filename. Exact name first; otherwise a
 * case-insensitive match that must be unique (Windows users routinely type
 * Derila.JPG for derila.jpg, but two files differing only by case is
 * ambiguous and is rejected rather than guessed).
 */
export function matchImage(filename: string, images: ManifestImage[]): ImageMatch {
  if (!checkCsvImageFilename(filename).ok) return { status: "missing", message: "Invalid image filename." };
  let hit = images.filter((i) => i.name === filename);
  if (hit.length === 0) hit = images.filter((i) => i.name.toLowerCase() === filename.toLowerCase());
  if (hit.length === 0) return { status: "missing", message: `No uploaded file named “${filename}”.` };
  if (hit.length > 1) return { status: "ambiguous", message: `More than one uploaded file matches “${filename}”.` };
  return verifyImage(hit[0]);
}

export function verifyImage(image: ManifestImage): ImageMatch {
  if (image.problem === "too-large") return { status: "too-large", message: "Image is larger than the 5 MB limit." };
  if (image.problem === "unreadable") return { status: "unreadable", message: "The image could not be read." };
  if (image.size === 0) return { status: "unreadable", message: "The image file is empty." };
  if (image.size > MAX_IMAGE_BYTES) return { status: "too-large", message: "Image is larger than the 5 MB limit." };
  if (image.size > MAX_BULK_UPLOAD_BYTES) {
    return { status: "too-large", message: "Image is larger than the 4 MB per-upload limit of this deployment — compress it." };
  }
  if (!image.sniffed || !ALLOWED_IMAGE_TYPES.has(image.sniffed)) {
    return { status: "unsupported", message: "Not a JPEG, PNG or WebP image (checked by file contents, not the name)." };
  }
  const claimed = claimedTypeFromName(image.name);
  if (claimed && claimed !== image.sniffed) {
    return { status: "mismatch", message: "The file extension doesn't match the file's actual contents." };
  }
  return { status: "matched", image };
}

/**
 * The image limit itself (MAX_IMAGE_BYTES, 5 MiB) is the existing product
 * rule and is unchanged. This is a separate, TRANSPORT limit: bulk import
 * sends one image per request, and the hosting platform (Vercel) rejects any
 * request body over 4.5 MB before the application sees it, multipart
 * overhead included. An image between ~4.1 and 5 MiB would therefore pass
 * every validation and then fail mid-import — leaving a half-done batch — so
 * it is stopped here, in the preview, with an actionable message.
 */
export const MAX_BULK_UPLOAD_BYTES = 4 * 1024 * 1024;

export type PreviewRow = {
  line: number;
  name: string;
  imageFilename: string;
  /** Canonical names of the categories this row will be assigned to. */
  categories: string[];
  image: { status: ImageMatch["status"] | "invalid-name"; label: string; matchedName: string | null };
  url: { status: ParsedRow["urlStatus"]; label: string };
  errors: string[];
  ok: boolean;
};

export type Preview = {
  fatal: string | null;
  rows: PreviewRow[];
  summary: {
    found: number;
    imagesMatched: number;
    missingImages: number;
    invalidUrls: number;
    duplicates: number;
    invalidCategories: number;
    errorRows: number;
    unusedImages: number;
  };
  /** True when the CSV carried a category column. */
  hasCategoryColumn: boolean;
  canImport: boolean;
};

export function emptyPreview(fatal: string): Preview {
  return {
    fatal,
    rows: [],
    summary: { found: 0, imagesMatched: 0, missingImages: 0, invalidUrls: 0, duplicates: 0, invalidCategories: 0, errorRows: 0, unusedImages: 0 },
    hasCategoryColumn: false,
    canImport: false,
  };
}

export function buildPreview(batch: ParsedBatch, images: ManifestImage[], existingBases: Set<string>, catalog: CategoryRef[] = []): Preview {
  if (batch.fatal) return emptyPreview(batch.fatal);

  const usedNames = new Set<string>();
  const rows: PreviewRow[] = batch.rows.map((row) => {
    const errors = [...row.errors];

    // Duplicate against the catalogue (slug-collision rule, see file header).
    if (row.duplicateOfLine === null && row.base && existingBases.has(row.base)) {
      errors.push("Duplicate product: an existing product already uses this name (its URL would get a “-2” suffix).");
    }

    errors.push(...categoryErrors(row, catalog));
    const categories = resolveCategories(row.categoryNames, catalog).names;

    const filenameOk = checkCsvImageFilename(row.imageFilename).ok;
    let image: PreviewRow["image"];
    if (!filenameOk) {
      image = { status: "invalid-name", label: "Invalid filename", matchedName: null };
    } else {
      const m = matchImage(row.imageFilename, images);
      if (m.status === "matched") {
        usedNames.add(m.image.name);
        image = { status: "matched", label: `Matched · ${(m.image.size / 1024).toFixed(0)} KB`, matchedName: m.image.name };
      } else {
        errors.push(`Image: ${m.message}`);
        image = { status: m.status, label: labelFor(m.status), matchedName: null };
      }
    }

    const url: PreviewRow["url"] = {
      status: row.urlStatus,
      label:
        row.urlStatus === "valid"
          ? `Valid · ${row.urlHost}${row.urlInsecure ? " (http, not encrypted)" : ""}`
          : row.urlStatus === "missing"
            ? "Missing"
            : "Invalid",
    };
    return { line: row.line, name: row.name, imageFilename: row.imageFilename, categories, image, url, errors, ok: errors.length === 0 };
  });

  const summary = {
    found: rows.length,
    imagesMatched: rows.filter((r) => r.image.status === "matched").length,
    missingImages: rows.filter((r) => r.image.status !== "matched").length,
    invalidUrls: rows.filter((r) => r.url.status !== "valid").length,
    duplicates: rows.filter((r) => r.errors.some((e) => e.startsWith("Duplicate product"))).length,
    invalidCategories: rows.filter((r) => r.errors.some((e) => e.startsWith("Category"))).length,
    errorRows: rows.filter((r) => !r.ok).length,
    unusedImages: images.filter((i) => !usedNames.has(i.name)).length,
  };
  return { fatal: null, rows, summary, hasCategoryColumn: batch.hasCategoryColumn, canImport: summary.errorRows === 0 && rows.length > 0 };
}

function labelFor(status: ImageMatch["status"]): string {
  switch (status) {
    case "missing": return "Missing";
    case "ambiguous": return "Ambiguous match";
    case "unsupported": return "Unsupported type";
    case "too-large": return "Too large";
    case "mismatch": return "Extension ≠ content";
    case "unreadable": return "Unreadable";
    default: return "Problem";
  }
}
