import { ImageResponse } from "next/og";

// The site's default social preview image, served at a stable /og-default.png
// (Step 7.10).
//
// WHY A ROUTE AND NOT THE opengraph-image FILE CONVENTION
// The file convention was tried first and measured. Its image only reaches a
// child segment that declares no openGraph object of its own: /about (which
// sets none) inherited it, while /products, /categories, /search and every
// detail page — all of which set openGraph for their title and url — resolved
// with no og:image at all. Since the fallback is needed precisely on those
// pages, the convention cannot deliver it. It also mangles the URL with a
// content hash (/opengraph-image-1c1a04?cacbc0cb...), so no other module can
// reference it.
//
// A route gives one stable, importable URL that every page can fall back to,
// with the precedence decided in our own code rather than by metadata merge
// rules.
//
// WHY GENERATED AND NOT A COMMITTED PNG
// next/og ships with Next.js, so this adds no dependency, and force-static
// means it is rendered once at build time and served as a plain static asset
// — no per-request work. A binary in the repository would instead have to be
// regenerated by hand and could not be reviewed in a diff.
//
// NO PRIVATE DATA: every value drawn here is a compile-time constant. Nothing
// is read from the database or the request, so no affiliate destination,
// draft content, or visitor data can reach the image.

export const dynamic = "force-static";

const SIZE = { width: 1200, height: 630 };

export function GET() {
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          padding: "80px 96px",
          background: "linear-gradient(135deg, #1b3c2a 0%, #244f37 55%, #2f6445 100%)",
          color: "#ffffff",
        }}
      >
        <div style={{ display: "flex", fontSize: 88, fontWeight: 700, letterSpacing: "-0.03em", lineHeight: 1.05 }}>
          Wellness Center
        </div>
        <div
          style={{
            display: "flex",
            fontSize: 88,
            fontWeight: 700,
            letterSpacing: "-0.03em",
            lineHeight: 1.05,
            color: "#b1d1bb",
          }}
        >
          USA
        </div>
        <div style={{ display: "flex", marginTop: 36, fontSize: 34, color: "#d7e8dc", lineHeight: 1.35 }}>
          Independent health and wellness product research
        </div>
      </div>
    ),
    SIZE,
  );
}
