import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { ImageResponse } from "next/og";

// The site's default social preview image, served at a stable /og-default.png
// (Step 7.10).
//
// WHY A ROUTE AND NOT THE opengraph-image FILE CONVENTION
// The file convention was tried first and measured. Its image only reaches a
// child segment that declares no openGraph object of its own: /about (which
// sets none) inherited it, while /products, /categories, /search and every
// detail page — all of which set openGraph for their title and url — resolved
// with no og:image at all. Since the fallback is needed precisely on those
// pages, the convention cannot deliver it. It also mangles the URL with a
// content hash (/opengraph-image-1c1a04?cacbc0cb...), so no other module can
// reference it.
//
// A route gives one stable, importable URL that every page can fall back to,
// with the precedence decided in our own code rather than by metadata merge
// rules.
//
// WHY GENERATED AND NOT A COMMITTED PNG
// next/og ships with Next.js, so this adds no dependency, and force-static
// means it is rendered once at build time and served as a plain static asset
// — no per-request work. A binary in the repository would instead have to be
// regenerated by hand and could not be reviewed in a diff.
//
// The card shows the official logo (src/assets/brand/logo.png, read from disk
// at build time and inlined as a data URI — next/og cannot import a static
// asset). It is drawn on the site's cream canvas colour because the artwork
// is dark-on-transparent.
//
// NO PRIVATE DATA: every value drawn here is a compile-time constant. Nothing
// is read from the database or the request, so no affiliate destination,
// draft content, or visitor data can reach the image.

export const dynamic = "force-static";

const SIZE = { width: 1200, height: 630 };

export async function GET() {
  const logo = await readFile(join(process.cwd(), "src/assets/brand/logo.png"));
  const src = `data:image/png;base64,${logo.toString("base64")}`;
  // The logo's intrinsic ratio is 960:577; 520px tall keeps it inside the
  // safe area of every platform's crop.
  const height = 520;
  const width = Math.round((height * 960) / 577);
  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          alignItems: "center",
          justifyContent: "center",
          background: "#faf8f4",
        }}
      >
        {/* eslint-disable-next-line @next/next/no-img-element -- next/og renders to an image; next/image is not applicable */}
        <img src={src} alt="Wellness Center USA" width={width} height={height} />
      </div>
    ),
    SIZE,
  );
}
